### Numpy

In [0]:
import numpy as np

In [0]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
a=np.ones(5)*5
a

array([5., 5., 5., 5., 5.])

In [0]:
a=np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [0]:
a[a%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
a=np.arange(10,51,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
print("rand number between 0, 1")
np.random.rand(1)

rand number between 0, 1


array([0.3298414])

In [9]:
print("an array of 25 random numbers sampled from std distribution")
np.random.randn(25)

an array of 25 random numbers sampled from std distribution


array([-0.08433949,  0.69571734, -0.96346939,  0.51822121,  0.50757866,
        0.4250752 , -0.60903802,  0.73386502,  0.78479335,  0.08003951,
        0.14652281, -0.46816282,  0.12352202, -0.664166  , -0.28132968,
        1.38518115, -0.78417244,  0.19644264,  0.14581218, -0.48891009,
        0.59799656,  1.57794783, -0.07205718,  0.2814476 ,  0.53564774])

In [0]:
np.random.normal()

array([[-1.77517455,  1.30434161, -0.00692572],
       [ 0.10599008, -1.7744466 , -0.10932419],
       [-1.00037259,  0.48239528, -0.52506551]])

In [0]:
np.random.normal(0,1,25)

array([-0.71256989, -0.25128808, -2.01095914, -0.50796722, -1.42911544,
       -0.58242339,  1.05862108,  0.00629808, -1.17508322,  0.23379925,
       -1.17215162,  0.08624081,  1.7882949 , -0.87206414,  0.02840475,
        0.421239  ,  1.08282562,  0.33137698, -0.48904678, -1.06773776,
        1.18739313, -0.26964169, -0.08395205,  0.44989935,  0.15163745])

In [4]:
m=np.arange(1,26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
print("mean std:",np.sum(m),np.std(m))

mean std: 325 7.211102550927978


In [33]:
print("mean std:",m.sum(),m.std())

mean std: 325 7.211102550927978


In [34]:
print("sum over columns")
sum(m[:])

array([55, 60, 65, 70, 75])

In [39]:
print("sum over columns")
m.sum(axis=0)


sum over columns


array([55, 60, 65, 70, 75])

In [38]:
print("sum over rows")
m.sum(axis=1)

sum over rows


array([ 15,  40,  65,  90, 115])

In [11]:
m[-1,:]

array([21, 22, 23, 24, 25])

In [12]:
m[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
m[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [29]:
m[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [7]:
m[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [8]:
m[3,4]

20

### Pandas Series

In [0]:
import numpy as np
import pandas as pd

In [44]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}
arr

array([10, 20, 30])

In [50]:
pd.Series(my_data)


0    10
1    20
2    30
dtype: int64

In [47]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [48]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [49]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [51]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [52]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

Compared to numpy array, pandas series can hold different object types

In [55]:
ser1=pd.Series([1,2,3,4],['a','b','c','d'])
ser1


a    1
b    2
c    3
d    4
dtype: int64

In [57]:
ser2=pd.Series([1,2,5,4],['a','b','e','d'])
ser2

a    1
b    2
e    5
d    4
dtype: int64

In [58]:
ser1['a']

1

In [61]:
ser3=pd.Series(data=labels)
ser3

0    a
1    b
2    c
dtype: object

In [62]:
ser3[0]

'a'

In [63]:
ser1+ser2

a    2.0
b    4.0
c    NaN
d    8.0
e    NaN
dtype: float64

Pandas converts all the info to float so we don't miss any information

In [0]:
import numpy as np
import pandas  as pd
from numpy.random import randn

In [0]:
np.random.seed(101)

### Pandas Dataframe

Data frame is a bunch of series that share the same index.
W X Y Z columns are panda series

In [13]:
df=pd.DataFrame(randn(5,4),['A','B','C', 'D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [70]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [71]:
type(df)

pandas.core.frame.DataFrame

In [73]:
type(df['W'])

pandas.core.series.Series

In [74]:
df[['W','Z']]

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [83]:
df['new']= df['W']+df['W']
df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  0.605331
B -0.134841  0.390528  0.166905  0.184502 -0.269681
C  0.807706  0.072960  0.638787  0.329646  1.615412
D -0.497104 -0.754070 -0.943406  0.484752 -0.994208
E -0.116773  1.901755  0.238127  1.996652 -0.233547

In [85]:
df.drop('new',axis=1)
df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  0.605331
B -0.134841  0.390528  0.166905  0.184502 -0.269681
C  0.807706  0.072960  0.638787  0.329646  1.615412
D -0.497104 -0.754070 -0.943406  0.484752 -0.994208
E -0.116773  1.901755  0.238127  1.996652 -0.233547

In [86]:
df.drop('new',axis=1,inplace=True)
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [87]:
df.drop('E',axis=0)

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [88]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [90]:
df.shape

(5, 4)

In [91]:
df[['X','Y']]

X         Y
A  1.693723 -1.706086
B  0.390528  0.166905
C  0.072960  0.638787
D -0.754070 -0.943406
E  1.901755  0.238127

In [92]:
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [93]:
df.iloc[2] #numeric index

W    0.807706
X    0.072960
Y    0.638787
Z    0.329646
Name: C, dtype: float64

In [94]:
df.loc['B','Y']

0.16690463609281317

In [96]:
df.loc[['A','B'],['W','Y']]

W         Y
A  0.302665 -1.706086
B -0.134841  0.166905

In [97]:
df[df>0]

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [98]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [100]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [99]:
df[df['W']>0]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [104]:
result=df[df['W']>0]  
result

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [105]:
result[['X','Y']]

X         Y
A  1.693723 -1.706086
C  0.072960  0.638787

In [107]:
df[df['W']>0][['X','Y']]

X         Y
A  1.693723 -1.706086
C  0.072960  0.638787

In [14]:
df[(df['W']>0) | (df['Y']>1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [16]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [18]:
newind='CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [24]:
df['States'] = newind
df

W         X         Y         Z States
States                                               
CA      2.706850  0.628133  0.907969  0.503826     CA
NY      0.651118 -0.319318 -0.848077  0.605965     NY
WY     -2.018168  0.740122  0.528813 -0.589001     WY
OR      0.188695 -0.758872 -0.933237  0.955057     OR
CO      0.190794  1.978757  2.605967  0.683509     CO

In [28]:
df['States'] = newind
df

W         X         Y         Z States
States                                               
CA      2.706850  0.628133  0.907969  0.503826     CA
NY      0.651118 -0.319318 -0.848077  0.605965     NY
WY     -2.018168  0.740122  0.528813 -0.589001     WY
OR      0.188695 -0.758872 -0.933237  0.955057     OR
CO      0.190794  1.978757  2.605967  0.683509     CO

In [30]:
df.set_index('States',inplace=True)
df

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [34]:
outside = ['G1']*3+['G2']*3
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [33]:
inside = [1,2,3,]*2
inside

[1, 2, 3, 1, 2, 3]

In [35]:
hier_index = list(zip(outside,inside))
hier_index 

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [36]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [0]:
from numpy.random import randn
import numpy as np

In [41]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

A         B
G1 1  1.025984 -0.156598
   2 -0.031579  0.649826
   3  2.154846 -0.610259
G2 1 -0.755325 -0.346419
   2  0.147027 -0.479448
   3  0.558769  1.024810

In [42]:
df.loc['G2'].loc[2]['B']

-0.47944803904109595

In [43]:
df

A         B
G1 1  1.025984 -0.156598
   2 -0.031579  0.649826
   3  2.154846 -0.610259
G2 1 -0.755325 -0.346419
   2  0.147027 -0.479448
   3  0.558769  1.024810

In [48]:
df.index.names = ['Groups','Num']
df

A         B
Groups Num                    
G1     1    1.025984 -0.156598
       2   -0.031579  0.649826
       3    2.154846 -0.610259
G2     1   -0.755325 -0.346419
       2    0.147027 -0.479448
       3    0.558769  1.024810

In [49]:
#for mult-level index

df.xs('G1')

A         B
Num                    
1    1.025984 -0.156598
2   -0.031579  0.649826
3    2.154846 -0.610259

In [51]:
df.loc['G1']

A         B
Num                    
1    1.025984 -0.156598
2   -0.031579  0.649826
3    2.154846 -0.610259

In [53]:
df.xs(1,level = 'Num')

A         B
Groups                    
G1      1.025984 -0.156598
G2     -0.755325 -0.346419

### Missing data

In [54]:
d = {'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[1,2,3]}
df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [55]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [56]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [59]:
# you drop >= threshold for nan occurance
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [61]:
df.fillna(value='Fill Val')
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [63]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [66]:
data = { 'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'Person':['Sam','Chalie','Amy','Vanessa','Carl','Sarah'],
        'Sales':[200,120,340,124,243,350]

}
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Chalie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [67]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG   Chalie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [0]:
bycomp=df.groupby('Company')

In [72]:
bycomp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [73]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [74]:
df.groupby('Company').std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [75]:
df.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [76]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [77]:
df.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [79]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

### Merge, join, concatinating

In [84]:
df1=pd.DataFrame(randn(5,4),['A','B','C', 'D','E'],['W','X','Y','Z'])
df1

W         X         Y         Z
A  0.975720 -0.388239  0.783316 -0.708954
B  0.586847 -1.621348  0.677535  0.026105
C -1.678284  0.333973 -0.532471  2.117727
D  0.197524  2.302987  0.729024 -0.863091
E  0.305632  0.243178  0.864165 -1.560931

In [81]:
df2=pd.DataFrame(randn(5,4),['A','B','C', 'D','E'],['WW','XX','YY','ZZ'])
df2

WW        XX        YY        ZZ
A  0.992573  1.192241 -1.046780  1.292765
B -1.467514 -0.494095 -0.162535  0.485809
C  0.392489  0.221491 -0.855196  1.541990
D  0.666319 -0.538235 -0.568581  1.407338
E  0.641806 -0.905100 -0.391157  1.028293

In [82]:
df3=pd.DataFrame(randn(5,4),['A','B','C', 'D','E'],['WWW','XXX','YYY','ZZZ'])
df3

WWW       XXX       YYY       ZZZ
A -1.972605 -0.866885  0.720788 -1.223082
B  1.606780 -1.115710 -1.385379 -1.329660
C  0.041460 -0.411055 -0.771329  0.110477
D -0.804652  0.253548  0.649148  0.358941
E -1.080471  0.902398  0.161781  0.833029

In [85]:
pd.concat([df1,df2,df3])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


W        WW       WWW  ...         Z        ZZ       ZZZ
A  0.975720       NaN       NaN  ... -0.708954       NaN       NaN
B  0.586847       NaN       NaN  ...  0.026105       NaN       NaN
C -1.678284       NaN       NaN  ...  2.117727       NaN       NaN
D  0.197524       NaN       NaN  ... -0.863091       NaN       NaN
E  0.305632       NaN       NaN  ... -1.560931       NaN       NaN
A       NaN  0.992573       NaN  ...       NaN  1.292765       NaN
B       NaN -1.467514       NaN  ...       NaN  0.485809       NaN
C       NaN  0.392489       NaN  ...       NaN  1.541990       NaN
D       NaN  0.666319       NaN  ...       NaN  1.407338       NaN
E       NaN  0.641806       NaN  ...       NaN  1.028293       NaN
A       NaN       NaN -1.972605  ...       NaN       NaN -1.223082
B       NaN       NaN  1.606780  ...       NaN       NaN -1.329660
C       NaN       NaN  0.041460  ...       NaN       NaN  0.110477
D       NaN       NaN -0.804652  ...       NaN       NaN  0.358941
E       NaN       NaN -1.080471  ...       NaN       NaN  0.833029

[15 rows x 12 columns]

In [86]:
pd.concat([df1,df2,df3],axis=1)

W         X         Y  ...       XXX       YYY       ZZZ
A  0.975720 -0.388239  0.783316  ... -0.866885  0.720788 -1.223082
B  0.586847 -1.621348  0.677535  ... -1.115710 -1.385379 -1.329660
C -1.678284  0.333973 -0.532471  ... -0.411055 -0.771329  0.110477
D  0.197524  2.302987  0.729024  ...  0.253548  0.649148  0.358941
E  0.305632  0.243178  0.864165  ...  0.902398  0.161781  0.833029

[5 rows x 12 columns]

In [3]:
d={'key1':['k0','k1','k2','k3'],
   'key2':['k0','k0','k0','k0'],
   'A':['A0','A1','A2','A3'],
   'B':['B0','B1','B2','B3']}
f1 = pd.DataFrame(d)
f1

key1 key2   A   B
0   k0   k0  A0  B0
1   k1   k0  A1  B1
2   k2   k0  A2  B2
3   k3   k0  A3  B3

In [4]:
d={'key1':['k0','k1','k2','k3'],
   'key2':['k0','k0','k0','k0'],
   'C':['C0','C1','C2','C3'],
   'D':['D0','D1','D2','D3']}
f2 = pd.DataFrame(d)
f2

key1 key2   C   D
0   k0   k0  C0  D0
1   k1   k0  C1  D1
2   k2   k0  C2  D2
3   k3   k0  C3  D3

In [97]:
pd.merge(f1,f2,how='inner',on='key1')

key1 key2_x   A   B key2_y   C   D
0   k0     k0  A0  B0     k0  C0  D0
1   k1     k0  A1  B1     k0  C1  D1
2   k2     k0  A2  B2     k0  C2  D2
3   k3     k0  A3  B3     k0  C3  D3

In [98]:
pd.merge(f1,f2,how='outer',on=['key1','key2'])

key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A1  B1  C1  D1
2   k2   k0  A2  B2  C2  D2
3   k3   k0  A3  B3  C3  D3

In [99]:
pd.merge(f1,f2,how='right',on=['key1','key2'])

key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A1  B1  C1  D1
2   k2   k0  A2  B2  C2  D2
3   k3   k0  A3  B3  C3  D3

In [5]:
pd.merge(f1,f2,how='left',on=['key1','key2'])

key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A1  B1  C1  D1
2   k2   k0  A2  B2  C2  D2
3   k3   k0  A3  B3  C3  D3

In [0]:
import pandas as pd
import numpy as np

In [11]:
f2['key2'].unique() #unique values

array(['k0'], dtype=object)

In [12]:
f2['key2'].nunique() #number of unique values

1

In [14]:
f2['key2'].value_counts()


k0    4
Name: key2, dtype: int64

In [15]:
f2['key1'].value_counts()


k0    1
k1    1
k2    1
k3    1
Name: key1, dtype: int64

In [18]:
f2[(f2['key1']== 'k0') & (f2['key2']=='k0')]

key1 key2   C   D
0   k0   k0  C0  D0

In [6]:
f2['E']=[1,2,3,4]
f2

key1 key2   C   D  E
0   k0   k0  C0  D0  1
1   k1   k0  C1  D1  2
2   k2   k0  C2  D2  3
3   k3   k0  C3  D3  4

In [7]:
f2['E'].sum()

10

### Apply a function

In [8]:
def times2(i):
    return 2*i
f2['E']=f2['E'].apply(times2)    
f2

key1 key2   C   D  E
0   k0   k0  C0  D0  2
1   k1   k0  C1  D1  4
2   k2   k0  C2  D2  6
3   k3   k0  C3  D3  8

In [14]:
f2['E'].apply(lambda x:x*2)


0     4
1     8
2    12
3    16
Name: E, dtype: int64

In [19]:
f2['key1']=['k1','k1','k2','k2']
f2['key2']=['k3','k3','k3','k4']
f2['D']=['x','y','x','y']
f2

key1 key2   C  D  E
0   k1   k3  C0  x  2
1   k1   k3  C1  y  4
2   k2   k3  C2  x  6
3   k2   k4  C3  y  8

In [20]:
f2.columns

Index(['key1', 'key2', 'C', 'D', 'E'], dtype='object')

In [21]:
f2.index

RangeIndex(start=0, stop=4, step=1)

In [56]:
f2.sort_values(by='E',ascending=False, inplace=True)
f2

key1 key2   C  D         E
3   k2   k4  C3  y  16777216
2   k2   k3  C2  x  12582912
1   k1   k3  C1  y   8388608
0   k1   k3  C0  x   4194304

In [22]:
f2.isnull()

key1   key2      C      D      E
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False

### make multindex for data frame columns

In [50]:
f2.pivot_table(values='E',index=['key2','key1'],columns=['C'])

C                 C0         C1          C2          C3
key2 key1                                              
k3   k1    4194304.0  8388608.0         NaN         NaN
     k2          NaN        NaN  12582912.0         NaN
k4   k2          NaN        NaN         NaN  16777216.0

You will need to install four libraries using pip or conda:

* conda install sqlalchemy
* conda install lxml
* conda install html5lib
* conda install BeautifulSoup4
* conda install xlrd (automaticaly installed usually)

In [23]:
d={
    'a':[0,4,8,12],
    'b':[1,5,9,13],
    'c':[2,6,10,14],
    'd':[3,7,11,15]
}

df=pd.DataFrame(d)
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [0]:
# to make sure we don't save the index as a column: index=False
df.to_csv('example.csv',index=False)


In [29]:
pd.read_csv('example.csv')


a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [32]:
!pip install xlrd 

Panda thinks a workbook is a bunch of sheet and each sheet is a dataframe

In [0]:
df.to_excel('example.xlsx',index=False)

In [37]:
pd.read_excel('example.xlsx',sheet_name='Sheet1')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### Read HTML Website: [link text](https://www.fdic.gov/bank/individual/failed/banklist.html)

In [0]:
data = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')

In [39]:
type(data)

list

### Read sql 

In [0]:
from sqlalchemy import create_engine

In [0]:
#create a small sql engine in memory
engine = create_engine('sqlite:///:memory:')

In [0]:
df.to_sql('my_table',engine)

In [47]:
sqldf = pd.read_sql('my_table',con=engine)
sqldf

index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15